var PLATFORM_NAMES = [
	"facebook",
	"kabam",
	"ios",
	"google",
	"android",
	"kabamguest",
	"viximo",
	"plinga",
	"tuenti",
	"orkut",
	"naszaklasa",
	"gaia",
	"yahoo",
	"myyearbook",
	"friendster",
	"vznet",
	"spielwiese",
	"odnoklassniki",
	"bebo",
	"cafemom",
	"lokalisten",
	"quepasa",
	"schuelervz",
	"studivz",
	"zoogr",
	"netlog",
	"badoo",
	"skyrock",
	"friendsreunited",
	"trombi",
	"hyves",
	"werkenntwen",
	"iwiwhu",
	"kwick",
	"vkontakte",
	"mailru",
	"kongregate",
	"jeuxfr",
	"spelletjesnl",
	"jetztspielende",
	"grypl",
	"gamesgamescom",
	"giociit",
	"jeufr",
	"spelnl",
	"spielencom",
	"agamecom",
	"spil",
	"steam",
	"rotmg",
	"mobage",
	"googleapp",
	"amazonapp",
	"xsolla"
];

var PLATFORM_IDS = {
	"facebook" : 0,
	"kabam" : 1,
	"ios" : 2,
	"google" : 3,
	"android" : 4,
	"kabamguest" : 5,
	"viximo" : 6,
	"plinga" : 7,
	"tuenti" : 8,
	"orkut" : 9,
	"naszaklasa" : 10,
	"gaia" : 11,
	"yahoo" : 12,
	"myyearbook" : 13,
	"friendster" : 14,
	"vznet" : 15,
	"spielwiese" : 16,
	"odnoklassniki" : 17,
	"bebo" : 18,
	"cafemom" : 19,
	"lokalisten" : 20,
	"quepasa" : 21,
	"schuelervz" : 22,
	"studivz" : 23,
	"zoogr" : 24,
	"netlog" : 25,
	"badoo" : 26,
	"skyrock" : 27,
	"friendsreunited" : 28,
	"trombi" : 29,
	"hyves" : 30,
	"werkenntwen" : 31,
	"iwiwhu" : 32,
	"kwick" : 33,
	"vkontakte" : 34,
	"mailru" : 35,
	"kongregate" : 36,
	"jeuxfr" : 37,
	"spelletjesnl" : 38,
	"jetztspielende" : 39,
	"grypl" : 40,
	"gamesgamescom" : 41,
	"giociit" : 42,
	"jeufr" : 43,
	"spelnl" : 44,
	"spielencom" : 45,
	"agamecom" : 46,
	"spil" : 47,
	"steam" : 48,
	"rotmg" : 49,
	"mobage" : 50,
	"googleapp" : 51,
	"amazonapp" : 52,
	"xsolla" : 53,
};